
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `views` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model views
 * 
 */
export type viewsModel = runtime.Types.Result.DefaultSelection<Prisma.$viewsPayload>

export type AggregateViews = {
  _count: ViewsCountAggregateOutputType | null
  _avg: ViewsAvgAggregateOutputType | null
  _sum: ViewsSumAggregateOutputType | null
  _min: ViewsMinAggregateOutputType | null
  _max: ViewsMaxAggregateOutputType | null
}

export type ViewsAvgAggregateOutputType = {
  count: number | null
}

export type ViewsSumAggregateOutputType = {
  count: bigint | null
}

export type ViewsMinAggregateOutputType = {
  slug: string | null
  count: bigint | null
}

export type ViewsMaxAggregateOutputType = {
  slug: string | null
  count: bigint | null
}

export type ViewsCountAggregateOutputType = {
  slug: number
  count: number
  _all: number
}


export type ViewsAvgAggregateInputType = {
  count?: true
}

export type ViewsSumAggregateInputType = {
  count?: true
}

export type ViewsMinAggregateInputType = {
  slug?: true
  count?: true
}

export type ViewsMaxAggregateInputType = {
  slug?: true
  count?: true
}

export type ViewsCountAggregateInputType = {
  slug?: true
  count?: true
  _all?: true
}

export type ViewsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which views to aggregate.
   */
  where?: Prisma.viewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of views to fetch.
   */
  orderBy?: Prisma.viewsOrderByWithRelationInput | Prisma.viewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.viewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned views
  **/
  _count?: true | ViewsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ViewsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ViewsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ViewsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ViewsMaxAggregateInputType
}

export type GetViewsAggregateType<T extends ViewsAggregateArgs> = {
      [P in keyof T & keyof AggregateViews]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateViews[P]>
    : Prisma.GetScalarType<T[P], AggregateViews[P]>
}




export type viewsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.viewsWhereInput
  orderBy?: Prisma.viewsOrderByWithAggregationInput | Prisma.viewsOrderByWithAggregationInput[]
  by: Prisma.ViewsScalarFieldEnum[] | Prisma.ViewsScalarFieldEnum
  having?: Prisma.viewsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ViewsCountAggregateInputType | true
  _avg?: ViewsAvgAggregateInputType
  _sum?: ViewsSumAggregateInputType
  _min?: ViewsMinAggregateInputType
  _max?: ViewsMaxAggregateInputType
}

export type ViewsGroupByOutputType = {
  slug: string
  count: bigint
  _count: ViewsCountAggregateOutputType | null
  _avg: ViewsAvgAggregateOutputType | null
  _sum: ViewsSumAggregateOutputType | null
  _min: ViewsMinAggregateOutputType | null
  _max: ViewsMaxAggregateOutputType | null
}

type GetViewsGroupByPayload<T extends viewsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ViewsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ViewsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ViewsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ViewsGroupByOutputType[P]>
      }
    >
  >



export type viewsWhereInput = {
  AND?: Prisma.viewsWhereInput | Prisma.viewsWhereInput[]
  OR?: Prisma.viewsWhereInput[]
  NOT?: Prisma.viewsWhereInput | Prisma.viewsWhereInput[]
  slug?: Prisma.StringFilter<"views"> | string
  count?: Prisma.BigIntFilter<"views"> | bigint | number
}

export type viewsOrderByWithRelationInput = {
  slug?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type viewsWhereUniqueInput = Prisma.AtLeast<{
  slug?: string
  AND?: Prisma.viewsWhereInput | Prisma.viewsWhereInput[]
  OR?: Prisma.viewsWhereInput[]
  NOT?: Prisma.viewsWhereInput | Prisma.viewsWhereInput[]
  count?: Prisma.BigIntFilter<"views"> | bigint | number
}, "slug">

export type viewsOrderByWithAggregationInput = {
  slug?: Prisma.SortOrder
  count?: Prisma.SortOrder
  _count?: Prisma.viewsCountOrderByAggregateInput
  _avg?: Prisma.viewsAvgOrderByAggregateInput
  _max?: Prisma.viewsMaxOrderByAggregateInput
  _min?: Prisma.viewsMinOrderByAggregateInput
  _sum?: Prisma.viewsSumOrderByAggregateInput
}

export type viewsScalarWhereWithAggregatesInput = {
  AND?: Prisma.viewsScalarWhereWithAggregatesInput | Prisma.viewsScalarWhereWithAggregatesInput[]
  OR?: Prisma.viewsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.viewsScalarWhereWithAggregatesInput | Prisma.viewsScalarWhereWithAggregatesInput[]
  slug?: Prisma.StringWithAggregatesFilter<"views"> | string
  count?: Prisma.BigIntWithAggregatesFilter<"views"> | bigint | number
}

export type viewsCreateInput = {
  slug: string
  count?: bigint | number
}

export type viewsUncheckedCreateInput = {
  slug: string
  count?: bigint | number
}

export type viewsUpdateInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type viewsUncheckedUpdateInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type viewsCreateManyInput = {
  slug: string
  count?: bigint | number
}

export type viewsUpdateManyMutationInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type viewsUncheckedUpdateManyInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  count?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
}

export type viewsCountOrderByAggregateInput = {
  slug?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type viewsAvgOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type viewsMaxOrderByAggregateInput = {
  slug?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type viewsMinOrderByAggregateInput = {
  slug?: Prisma.SortOrder
  count?: Prisma.SortOrder
}

export type viewsSumOrderByAggregateInput = {
  count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BigIntFieldUpdateOperationsInput = {
  set?: bigint | number
  increment?: bigint | number
  decrement?: bigint | number
  multiply?: bigint | number
  divide?: bigint | number
}



export type viewsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slug?: boolean
  count?: boolean
}, ExtArgs["result"]["views"]>

export type viewsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slug?: boolean
  count?: boolean
}, ExtArgs["result"]["views"]>

export type viewsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slug?: boolean
  count?: boolean
}, ExtArgs["result"]["views"]>

export type viewsSelectScalar = {
  slug?: boolean
  count?: boolean
}

export type viewsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"slug" | "count", ExtArgs["result"]["views"]>

export type $viewsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "views"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    slug: string
    count: bigint
  }, ExtArgs["result"]["views"]>
  composites: {}
}

export type viewsGetPayload<S extends boolean | null | undefined | viewsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$viewsPayload, S>

export type viewsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<viewsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ViewsCountAggregateInputType | true
  }

export interface viewsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['views'], meta: { name: 'views' } }
  /**
   * Find zero or one Views that matches the filter.
   * @param {viewsFindUniqueArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends viewsFindUniqueArgs>(args: Prisma.SelectSubset<T, viewsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Views that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {viewsFindUniqueOrThrowArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends viewsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, viewsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Views that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {viewsFindFirstArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends viewsFindFirstArgs>(args?: Prisma.SelectSubset<T, viewsFindFirstArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Views that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {viewsFindFirstOrThrowArgs} args - Arguments to find a Views
   * @example
   * // Get one Views
   * const views = await prisma.views.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends viewsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, viewsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Views that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {viewsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Views
   * const views = await prisma.views.findMany()
   * 
   * // Get first 10 Views
   * const views = await prisma.views.findMany({ take: 10 })
   * 
   * // Only select the `slug`
   * const viewsWithSlugOnly = await prisma.views.findMany({ select: { slug: true } })
   * 
   */
  findMany<T extends viewsFindManyArgs>(args?: Prisma.SelectSubset<T, viewsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Views.
   * @param {viewsCreateArgs} args - Arguments to create a Views.
   * @example
   * // Create one Views
   * const Views = await prisma.views.create({
   *   data: {
   *     // ... data to create a Views
   *   }
   * })
   * 
   */
  create<T extends viewsCreateArgs>(args: Prisma.SelectSubset<T, viewsCreateArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Views.
   * @param {viewsCreateManyArgs} args - Arguments to create many Views.
   * @example
   * // Create many Views
   * const views = await prisma.views.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends viewsCreateManyArgs>(args?: Prisma.SelectSubset<T, viewsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Views and returns the data saved in the database.
   * @param {viewsCreateManyAndReturnArgs} args - Arguments to create many Views.
   * @example
   * // Create many Views
   * const views = await prisma.views.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Views and only return the `slug`
   * const viewsWithSlugOnly = await prisma.views.createManyAndReturn({
   *   select: { slug: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends viewsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, viewsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Views.
   * @param {viewsDeleteArgs} args - Arguments to delete one Views.
   * @example
   * // Delete one Views
   * const Views = await prisma.views.delete({
   *   where: {
   *     // ... filter to delete one Views
   *   }
   * })
   * 
   */
  delete<T extends viewsDeleteArgs>(args: Prisma.SelectSubset<T, viewsDeleteArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Views.
   * @param {viewsUpdateArgs} args - Arguments to update one Views.
   * @example
   * // Update one Views
   * const views = await prisma.views.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends viewsUpdateArgs>(args: Prisma.SelectSubset<T, viewsUpdateArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Views.
   * @param {viewsDeleteManyArgs} args - Arguments to filter Views to delete.
   * @example
   * // Delete a few Views
   * const { count } = await prisma.views.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends viewsDeleteManyArgs>(args?: Prisma.SelectSubset<T, viewsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {viewsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Views
   * const views = await prisma.views.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends viewsUpdateManyArgs>(args: Prisma.SelectSubset<T, viewsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Views and returns the data updated in the database.
   * @param {viewsUpdateManyAndReturnArgs} args - Arguments to update many Views.
   * @example
   * // Update many Views
   * const views = await prisma.views.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Views and only return the `slug`
   * const viewsWithSlugOnly = await prisma.views.updateManyAndReturn({
   *   select: { slug: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends viewsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, viewsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Views.
   * @param {viewsUpsertArgs} args - Arguments to update or create a Views.
   * @example
   * // Update or create a Views
   * const views = await prisma.views.upsert({
   *   create: {
   *     // ... data to create a Views
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Views we want to update
   *   }
   * })
   */
  upsert<T extends viewsUpsertArgs>(args: Prisma.SelectSubset<T, viewsUpsertArgs<ExtArgs>>): Prisma.Prisma__viewsClient<runtime.Types.Result.GetResult<Prisma.$viewsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {viewsCountArgs} args - Arguments to filter Views to count.
   * @example
   * // Count the number of Views
   * const count = await prisma.views.count({
   *   where: {
   *     // ... the filter for the Views we want to count
   *   }
   * })
  **/
  count<T extends viewsCountArgs>(
    args?: Prisma.Subset<T, viewsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ViewsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ViewsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ViewsAggregateArgs>(args: Prisma.Subset<T, ViewsAggregateArgs>): Prisma.PrismaPromise<GetViewsAggregateType<T>>

  /**
   * Group by Views.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {viewsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends viewsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: viewsGroupByArgs['orderBy'] }
      : { orderBy?: viewsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, viewsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetViewsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the views model
 */
readonly fields: viewsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for views.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__viewsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the views model
 */
export interface viewsFieldRefs {
  readonly slug: Prisma.FieldRef<"views", 'String'>
  readonly count: Prisma.FieldRef<"views", 'BigInt'>
}
    

// Custom InputTypes
/**
 * views findUnique
 */
export type viewsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * Filter, which views to fetch.
   */
  where: Prisma.viewsWhereUniqueInput
}

/**
 * views findUniqueOrThrow
 */
export type viewsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * Filter, which views to fetch.
   */
  where: Prisma.viewsWhereUniqueInput
}

/**
 * views findFirst
 */
export type viewsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * Filter, which views to fetch.
   */
  where?: Prisma.viewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of views to fetch.
   */
  orderBy?: Prisma.viewsOrderByWithRelationInput | Prisma.viewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for views.
   */
  cursor?: Prisma.viewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of views.
   */
  distinct?: Prisma.ViewsScalarFieldEnum | Prisma.ViewsScalarFieldEnum[]
}

/**
 * views findFirstOrThrow
 */
export type viewsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * Filter, which views to fetch.
   */
  where?: Prisma.viewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of views to fetch.
   */
  orderBy?: Prisma.viewsOrderByWithRelationInput | Prisma.viewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for views.
   */
  cursor?: Prisma.viewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` views.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of views.
   */
  distinct?: Prisma.ViewsScalarFieldEnum | Prisma.ViewsScalarFieldEnum[]
}

/**
 * views findMany
 */
export type viewsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * Filter, which views to fetch.
   */
  where?: Prisma.viewsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of views to fetch.
   */
  orderBy?: Prisma.viewsOrderByWithRelationInput | Prisma.viewsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing views.
   */
  cursor?: Prisma.viewsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` views from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` views.
   */
  skip?: number
  distinct?: Prisma.ViewsScalarFieldEnum | Prisma.ViewsScalarFieldEnum[]
}

/**
 * views create
 */
export type viewsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * The data needed to create a views.
   */
  data: Prisma.XOR<Prisma.viewsCreateInput, Prisma.viewsUncheckedCreateInput>
}

/**
 * views createMany
 */
export type viewsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many views.
   */
  data: Prisma.viewsCreateManyInput | Prisma.viewsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * views createManyAndReturn
 */
export type viewsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * The data used to create many views.
   */
  data: Prisma.viewsCreateManyInput | Prisma.viewsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * views update
 */
export type viewsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * The data needed to update a views.
   */
  data: Prisma.XOR<Prisma.viewsUpdateInput, Prisma.viewsUncheckedUpdateInput>
  /**
   * Choose, which views to update.
   */
  where: Prisma.viewsWhereUniqueInput
}

/**
 * views updateMany
 */
export type viewsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update views.
   */
  data: Prisma.XOR<Prisma.viewsUpdateManyMutationInput, Prisma.viewsUncheckedUpdateManyInput>
  /**
   * Filter which views to update
   */
  where?: Prisma.viewsWhereInput
  /**
   * Limit how many views to update.
   */
  limit?: number
}

/**
 * views updateManyAndReturn
 */
export type viewsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * The data used to update views.
   */
  data: Prisma.XOR<Prisma.viewsUpdateManyMutationInput, Prisma.viewsUncheckedUpdateManyInput>
  /**
   * Filter which views to update
   */
  where?: Prisma.viewsWhereInput
  /**
   * Limit how many views to update.
   */
  limit?: number
}

/**
 * views upsert
 */
export type viewsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * The filter to search for the views to update in case it exists.
   */
  where: Prisma.viewsWhereUniqueInput
  /**
   * In case the views found by the `where` argument doesn't exist, create a new views with this data.
   */
  create: Prisma.XOR<Prisma.viewsCreateInput, Prisma.viewsUncheckedCreateInput>
  /**
   * In case the views was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.viewsUpdateInput, Prisma.viewsUncheckedUpdateInput>
}

/**
 * views delete
 */
export type viewsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
  /**
   * Filter which views to delete.
   */
  where: Prisma.viewsWhereUniqueInput
}

/**
 * views deleteMany
 */
export type viewsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which views to delete
   */
  where?: Prisma.viewsWhereInput
  /**
   * Limit how many views to delete.
   */
  limit?: number
}

/**
 * views without action
 */
export type viewsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the views
   */
  select?: Prisma.viewsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the views
   */
  omit?: Prisma.viewsOmit<ExtArgs> | null
}
